channels:
    - conda-forge
dependencies:
    - appmode
    - matplotlib
    - numpy
    - pandas
    - scipy
    - pip:
        - nnfigs
        - jupyterlab==3
        - ipywidgets
        - ipympl
        - plotly
        - statsmodels
